README.md, building.md, config/gameplay.md, config/other.md, config/performance.md, index.md, mkdocs.yml
This uses mkdocs so you will have to enable that on read the docs
You will also have to configure the paper spigot documentation to point to PaperDocs
=> Add documentation for 1.7.10

config/gameplay.md, config/other.md, config/performance.md, index.md
=> Fix indents, making the markdown render correctly

index.md
Add documentation for PR PaperSpigot/Paper#1 (i'm just assuming it will be pulled)
=> Document PaperSpigot/Paper@c6a0c56 (Optimize Spigot's Anti X-Ray)

source/server/configuration.rst
I looked back through these docs again after my last PR and found a few issues
and awkward grammar, so this new PR should fix them up.
Most of these changes are adding a period to the end of sentences, and changing some awkward or misleading phrases, and adding detail for why you might want a specific option.
I'm not actually sure how fast a player moves with respect to `baby-zombie-movement-speed`, I made up a value by judging how fast a baby zombie moves relative to me walking in a paper server. It's not obvious from the decompiled code how speed is calculated.
=> Fixup a bunch of miscellaneous issues.

source/about/faq.rst
=> implement docs link

source/server/configuration.rst
Added/re-ordered the newer configuration options.
=> Update Paper config documentation

source/server/configuration.rst
=> Update configuration docs

source/server/configuration.rst
Documented new config flags added after build 339
=> Added missing configuration flags

source/server/getting-started.rst
Added Java 11 Warning for new servers.
=> Added Java 11 Warning

source/server/configuration.rst
=> document per-world spawn-limits

source/java-update/index.rst
=> apt update

source/server/configuration.rst
This is an attempt at documenting item-validation (PaperMC/Paper#5775), however being honest I'm not overly happy with it but I don't see another better way to put it.
=> document item-validation

source/server/configuration.rst
=> Add docs for allow-player-cramming-damage

source/server/configuration.rst
This adds docs for the config options of PaperMC/Paper#6027
=> Add sensor and behavior tick rate doc

source/server/configuration.rst
=> Add timings.url docs

requirements.txt, source/conf.py
=> add Open Graph support

source/server/configuration.rst
Documentation for https://github.com/PaperMC/Paper/commit/7d10cdea0358854138d0d0ada5e74c58c688dea7, takes from/inspired by [the tuinity doucmentation](https://github.com/Tuinity/Tuinity/wiki/Config) as well as [this commit message](https://github.com/PaperMC/Paper/blob/20903fcf5e227a1a03e2afd89f01bfe951b2b328/patches/server/0771-Replace-player-chunk-loader-system.patch).
Closes #108
=> document Tuinity merge

source/server/configuration.rst
Fixed typos and writing issues here and there. Interesting read nevertheless!
=> Fix typos/writing issues in configuration.rst

source/server/configuration.rst
For https://github.com/PaperMC/Paper/pull/6837
=> Document that -1 spawner tick rate will disable spawners

source/server/configuration.rst
Documentation for PaperMC/Paper#6318
=> hide-itemmeta-from-clients documentation

source/site/api.rst
=> Display API versions table and organize wording

source/server/configuration.rst
Documents PaperMC/Paper@503ac8f
=> Documentation for perform-username-validation

source/server/configuration.rst
Fixes a couple of things I noticed
=> Minor grammar fixes

source/server/configuration.rst
=> slime-spawn-height docs
