- building.md
Users can download Paper 1.10 instead of 1.9 now
> Update version in docs

- source/about/contact.rst
Was looking at the page for some weird reason and noticed the typo on the Twitter handle. Also changed the IRC channel names to lower case.
> Fix typo on "Contact Us" page

- source/server/configuration.rst
Adds lava-obscures option to the wiki documentation.
> Add lava-obscures to Paper configuration documentation

- source/server/configuration.rst
Added documentation for PaperMC/Paper#4074. I also fixed the spacing for `hidden-blocks` below as I noticed it was incorrect, I did not check for correct spacing anywhere else.
> Document anti-xray's use-permission

- source/server/configuration.rst
Adds documentation for:
* use-display-name-in-quit-message
* track-plugin-scoreboards
* map-item-frame-cursor-limit
* seed-based-feature-search
* only-players-collide
* allow-vehicle-collisions
* portal-search-vanilla-dimension-scaling
* fix-items-merging-through-walls
* disable-mob-spawner-spawn-egg-transformation
* fix-invulnerable-end-crystal-exploit
* max-growth-height.bamboo
which I believe to be the only currently undocumented config options in paper.yml. Also fixes a small warning during build.
I'm not so sure about my documentation of `use-display-name-in-quit-message` as it does not provide any more information than what you could get by reading the configuration name, however, I'm not sure of a better way to phrase it or what to add.
> Document undocumented config options.

- source/java-update/index.rst
Apparently people are copy-pasting this without adjusting the path to the real one, lets just use the same directory name which was used before in the guide so that will at least match if they are copy pasting all of it instead of directly unpacking/adjusting the version numbers.
> Use a more appropriate JAVA_HOME path

- source/java-update/index.rst
These are the same commands taken from the original AdoptOpenJDK website before they changed the page to show different commands.
The reasoning for the change is that this is a more user-friendly / easier way to install AdoptOpenJDK on Debian-based distributions. I prefer this set of commands as it requires virtually no additional user input (unlike AdoptOpenJDK's guide). It is likely less confusing for users who are incapable of reading and just copy-paste stuff.
> Add our own guide for Debian AdoptOpenJDK

- source/server/configuration.rst
adds a warning about `seed-based-feature-search-loads-chunks` and updates default
recent change: https://github.com/PaperMC/Paper/commit/903fa9a33fcaab03e67343d010558c738bcea84e
> update `seed-based-feature-search-loads-chunks` to reflect recent change

- source/java-update/index.rst
It is named in the windows config window for a reason, lets use the name (along side a general description in case of a non-English interface) to make it more clear that this needs to be a System variable, not a user one!)
> Improve JAVA_HOME and Path explanation under Windows

- source/server/configuration.rst
Adds the config setting for the named entity deaths setting (Paper PR: https://github.com/PaperMC/Paper/pull/6107)
> Add named entity death setting

- source/site/api.rst
Even if these docs are not used, the v1 docs should be removed to prevent people from ignoring the deprecation notice and using it.
I probably missed a few things, and went over the 80 character line limit a few times, so I don't expect this to be merged as-is.
> Update documentation for version 2 of the API

- source/server/configuration.rst
Many people have been under the impression that this setting multiplies the mob cap by the number of players and uses that instead (which wouldn't even make sense as that would mean you can normally only have 70 monsters, but I digress).
> Update per-player-mob-spawns documentation to reduce confusion

- requirements.txt
- source/conf.py
- source/java-update/index.rst
This uses corretto specifically for RPM-based distros as Adopt's packaging makes it harder to idiot-proof, and is not up to date with modern releases, for example install will fail on openSUSE 15.3 using their instructions without manually modifying it to grab packages for 15.2, which is more complicated than I'd like to put here. yum/dnf also do not seem to have a variable for distro name like they do for release and architecture, making more manual editing required.
This also adds the tabs plugin, which looks like this:
Another consideration is which package managers to include, the main ones being DNF, yum, and zypper. I made the decision here to include both dnf and yum, defaulting to dnf as that's hopefully what most people will be running (eg. not cent 6), and it seems that's what …
> add RPM-based distros to java update guide

- source/server/configuration.rst
Update to mapped names and changed defaults and also add explanation that -1 means Vanilla behavior.
Didn't notice the PR that changes those before my docs PR :eyes:
> Update to mapped names and changed defaults.

- source/java-update/index.rst
The AdoptOpenJDK.net website no longer contains latest builds of Java as they are moving to the Adoptium.net domain and brand for [several reasons](https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/). This updates the links to the new website offering the latest builds where new ones are available (brew and apt repo seem to still run under the old name, at least I couldn't find new info yet and their [installation page](https://adoptium.net/installation.html?variant=openjdk16&jvmVariant=hotspot) isn't finished at this time)
> Link to new Adoptium website where possible

- source/java-update/index.rst
MCProHosting defaults their *Snapshot* image to Java 17 now due to it being LTS.
> Update MCProHosting to reflect Java 17

- source/server/configuration.rst
This PR remove a config related to a patch removed since 1.18 because mojang already fix this.
https://bugs.mojang.com/browse/MC-29274
https://github.com/PaperMC/Paper/blob/master/patches/removed/1.18/No%20longer%20needed/0626-MC-29274-Fix-Wither-hostility-towards-players.patch
> Remove unused wither bug config

- source/server/configuration.rst
Kenny changed the default to false in [this commit](https://github.com/PaperMC/Paper/commit/892c292dc9c712332671966965b1f508d41471b4).
> Correct default value for item obfuscation

- source/server/aikar-tuning.rst
- source/server/getting-started.rst
- source/server/index.rst
I noticed Aikar's blog has been getting quite sluggish lately, which I believe stops a good amount of people from learning what the flags are actually *doing* on their server. I did create a mirror of Aikar's blog post; however, after thinking a bit, I realized it's probably better to be in the docs itself as that'll be more official-looking than some random website that mirrors the content of the page. 
This PR keeps all the same content found on Aikar's blog post, just formatted slightly differently due to how RTD renders. I tried to keep each line in the file under a certain amount of characters, so you aren't horizontally scrolling through the blocks of text when updating/editing anything.
> Adding a page for Aikar's tunings to PaperDocs

- source/server/configuration.rst
Paper's documentation in relation to the `async-chunks` config option seemed to be misleading when looking at the actual code:
```java
int threads = getInt("settings.async-chunks.threads", -1);
int cpus = Runtime.getRuntime().availableProcessors() / 2;
if (threads <= 0) {
if (cpus <= 4) {
threads = cpus <= 2 ? 1 : 2;
} else {
threads = (int) Math.min(Integer.getInteger("paper.maxChunkThreads", 4), cpus / 2);
}
}
```
> Improve async-chunks documentation

- source/server/configuration.rst
The default is set to "false" here because there is an open PR on Paper to change the default value.
Paper PR: https://github.com/PaperMC/Paper/pull/7342
> Document 'hopper.ignore-occluding-blocks'
